# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ddbd5ac228440e0a5612b4cf862ef4afc422021c8c59b3cccb6ac3b29d56532438784d1e3a9007411f3558b5e31828f4abdc96529d4627b39c7745c2afdd96

test:
  secret_key_base: 8449dfe9203e89a75eae5b139368416692f28c6438fe0bbded63fea4bd823a31f8e2be305ccf069808acb00cf246be1df0622d3b1e16429a0452ed85f75563ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
